// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bootstrapGewekeCpp
List bootstrapGewekeCpp(NumericVector chain, int B, int n, double frac1, double frac2, double confidence_level);
RcppExport SEXP _bootGeweke_bootstrapGewekeCpp(SEXP chainSEXP, SEXP BSEXP, SEXP nSEXP, SEXP frac1SEXP, SEXP frac2SEXP, SEXP confidence_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type chain(chainSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type frac1(frac1SEXP);
    Rcpp::traits::input_parameter< double >::type frac2(frac2SEXP);
    Rcpp::traits::input_parameter< double >::type confidence_level(confidence_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrapGewekeCpp(chain, B, n, frac1, frac2, confidence_level));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bootGeweke_bootstrapGewekeCpp", (DL_FUNC) &_bootGeweke_bootstrapGewekeCpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_bootGeweke(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
